aquaMarket_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = "shop"
urlpatterns = [
    path('', views.index, name="index"),
    path('category/<str:category>', views.ProductCategory.as_view(), name="product_category"),
    path('about/', views.about, name="about"),
    path('search/', views.ProductSearch.as_view(), name="product_search"),
    path('product/<str:slug>/', views.ProductDetails.as_view(), name="product_detail")

]

shop/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify
from .assist import IntegerRangeField
import unidecode
# Create your models here.

CATEGORY_CHOICES=(
    ("saltwater_fish","ماهی آب شور"),
    ("freshwater_fish","ماهی آب شیرین"),
    ("supplies","وسایل و تجهیزات"),
    ("reef","ریف")
)

TYPE_CHOICES=(
    ("food","غذا"),
    ("air_pump","پمپ هوا"),
    ("skimmer","اسکیمر"),
    ("water_pump","واتر پمپ"),
    ("wave_maker","موج ساز"),
    ("medicine","دارو"),
    ("complement","مکمل"),
    ("aquarium","آکواریوم"),
    ("filter","فیلتر"),
    ("test","تست"),
    ("light","نور"),
    ("reactor","راکتور"),
    ("media","مدیا"),
    ("wood","چوب"),
    ("heater","بخاری"),
    ("other","سایر")
)
TYPE_CHOICES_VAL=["food","air_pump"]

class Shop(models.Model):
    name=models.CharField(max_length=30)
    email=models.EmailField(blank=True)
    addres=models.CharField(max_length=150)
    telegram_link=models.URLField(blank=True)
    instagram_link=models.URLField(blank=True)
    open_time = models.CharField(blank=True,max_length=15)
    def __str__(self):
        return self.name

class ShopNumber(models.Model):
    shop=models.ForeignKey(Shop,on_delete=models.CASCADE,related_name="shop_number")
    phone = models.CharField(max_length=20)
    def __str__(self):
        return self.shop.name


class Product(models.Model):
    title=models.CharField(max_length=50)
    description=models.CharField(max_length=500, blank=True)
    category= models.CharField(max_length=30,choices=CATEGORY_CHOICES)
    created_time=models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=100,blank=True, null=True,allow_unicode=True)
    image=models.ImageField(upload_to="shop/image_product",blank=True)
    brand=models.CharField(max_length=100,blank=True)
    orginal_price=models.DecimalField(max_digits=10, decimal_places=2,blank=True)
    final_price=models.DecimalField(max_digits=10,decimal_places=2,blank=True)
    type=models.CharField(max_length=100,blank=True,choices=TYPE_CHOICES)
    has_offer=models.BooleanField()
    exist=models.BooleanField()

    def save(self, *args, **kwargs):
        if self.slug is None:
            self.slug = self.title.replace(" ","_")
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

class ProductImage (models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    title = models.TextField(max_length=20,blank=True)
    image = models.ImageField(upload_to="shop/image_product")

    def __str__(self):
        return self.title + '   ('+self.product.title + ')'

class Customer(models.Model):
    phone = models.CharField(max_length=11,default=00000000000)

    def __str__(self):
        return self.phone

class Slider(models.Model):
    image=models.ImageField(upload_to="shop/image_slider")
    url=models.TextField(blank=True,max_length=50)

shop/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Product, Customer, ProductImage, TYPE_CHOICES, CATEGORY_CHOICES
import re

# Create your views here.

INDEX_LASTPRODUCT_NUMBER = 10
NUMBER_OF_RELATED_PRODUCT = 3
SEARCH_PAGINATE = 4
CATEGORY_PAGINATE = 4


def phone_Valid(s):
    Pattern = re.compile("(0/91)?[0-9]{11}")
    return Pattern.match(s)


def about(request):
    return render(request, "shop/about.html")


def index(request):
    products = Product.objects.all()
    reef_list = products.filter(category='reef').order_by('created_time')[0:INDEX_LASTPRODUCT_NUMBER]
    salt_fish_list = products.filter(category='saltwater_fish').order_by('created_time')[0:INDEX_LASTPRODUCT_NUMBER]
    fresh_fish_list = products.filter(category='freshwater_fish').order_by('created_time')[0:INDEX_LASTPRODUCT_NUMBER]
    supplies_list = products.filter(category='supplies').order_by('created_time')[0:INDEX_LASTPRODUCT_NUMBER]
    offer_products_list = products.filter(has_offer=1).order_by('created_time')[0:INDEX_LASTPRODUCT_NUMBER]
    if request.method == "POST":
        phone = request.POST.get('phone')
        if phone is not None:
            if (len(phone) > 6 and len(phone) < 12 and phone_Valid(phone)):
                # has_phone = True
                if (not Customer.objects.filter(phone=phone).exists()):
                    Customer.objects.create(phone=phone)

    return render(request,
                  'shop/index.html',
                  {'reef_list': reef_list,
                   'salt_fish_list': salt_fish_list,
                   'fresh_fish_list': fresh_fish_list,
                   'supplies_list': supplies_list,
                   'offer_products_list': offer_products_list
                   })


class ProductCategory(ListView):
    model = Product
    template_name = 'shop/category.html'
    paginate_by = CATEGORY_PAGINATE

    types = {}
    for type in TYPE_CHOICES:
        types[type[0]] = type[1]
    categories = {}
    for category in CATEGORY_CHOICES:
        categories[category[0]] = category[1]

    def get_queryset(self):
        self.category = self.kwargs['category']
        if self.category in self.categories.keys():
            return self.model.objects.filter(category=self.category).order_by("created_time")
        elif self.category in self.types.keys():
            return self.model.objects.filter(type=self.category).order_by("created_time")
        else:
            return self.model.objects.none()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductCategory, self).get_context_data(**kwargs)
        context['product_category'] = self.category
        if self.category == "supplies" or self.category in self.types.keys():
            context['has_type'] = True
            context['types'] = self.types
        else:
            context['has_type'] = False
        return context


class ProductSearch(ListView):
    model = Product
    template_name = "shop/product_search.html"

    def get_queryset(self):
        self.search_key = self.request.GET.get("Search")
        self.queris = self.request.GET
        if self.search_key:
            self.product = Product.objects.filter(title__icontains=self.search_key)
            # check product exist
            try:
                self.product[0]
                self.not_found = False
                self.paginate_by = SEARCH_PAGINATE
                return self.product
            except IndexError:
                self.not_found = True

        else:
            return Product.objects.none()

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductSearch, self).get_context_data(**kwargs)
        s = str(self.request.get_full_path())
        if s.__contains__("&page"):
            context['full_path'] = self.request.get_full_path()[0:s.index("&page")]
        else:
            context['full_path'] = self.request.get_full_path()
        context['not_found'] = self.not_found
        context['search_key'] = self.search_key
        return context


class ProductDetails(DetailView):
    model = Product
    template_name = "shop/product_detail.html"

    def get_queryset(self):
        self.slug = self.kwargs['slug']
        self.product = Product.objects.filter(slug=self.slug)
        return self.product

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductDetails, self).get_context_data(**kwargs)
        if self.get_object().category == "supplies":
            related_products = Product.objects.filter(type = self.get_object().type).order_by('created_time')[
                               0:NUMBER_OF_RELATED_PRODUCT]
        else:
            related_products = Product.objects.filter(category=self.get_object().category).order_by('created_time')[
                           0:NUMBER_OF_RELATED_PRODUCT]
        related_list = list(related_products)
        images = ProductImage.objects.filter(product=self.product[0])
        if self.get_object() in related_products:
            related_list.remove(self.get_object())
        context['related_products'] = related_list
        context['images'] = images
        return context

templates/shop/catagori.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center"
             data-background="{% static "/img/hero/category.jpg" %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>محصولات</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

    <!-- product list part start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="product_sidebar">
                        <div class="single_sedebar">
                            <form method="get" action="{% url "shop:product_search" %}" >
                                <input type="text" name="Search" value="{{ request.Get.q }}" placeholder="جستجوی محصول"
                                               style="direction: rtl; text-align: right; padding-right: 50px;">
                                <i class="ti-search"></i>
                            </form>

                        </div>
                        <div class="single_sedebar">
                            <div class="select_option" style="font-size: 120%">
                                <div class="select_option_list" style="text-align: right; padding-right: 50px">طبقه بندی<i
                                        class="right fas fa-caret-down"></i></div>
                                <div class="select_option_dropdown" style="text-align: right; padding-right: 50px">
                                    <pre><a href="{% url "shop:product_category" 'saltwater_fish'%}">ماهی آب شور</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'freshwater_fish'%}">ماهی آب شیرین</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'reef'%}">ریف</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'supplies'%}">غذا و تجهیزات</a></pre>
                                </div>
                            </div>
                        </div>
                        {% if has_type %}
                            <div class="single_sedebar">
                                <div class="select_option">
                                    <div class="select_option_list"
                                         style="text-align: right; padding-right: 50px;font-size: 120%">نوع<i
                                            class="right fas fa-caret-down"></i></div>
                                    <div class="select_option_dropdown" style="text-align: right; padding-right: 50px;">
                                        {% for type in types %}
                                            <pre style="font-size: 120%"><a href="#">{{ type }}</a></pre>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="product_list">
                        <div class="row">
                            {% for product in object_list %}
                                <div class="col-lg-6 col-sm-6">
                                    <div class="single_product_item">
                                        <a href="{% url "shop:product_detail" product.slug  %}"><img href="{{ product.slug }}" src="{{ product.image.url }}" alt="" class="img-fluid"></a>
                                        <div class="product-caption" style="text-align: center">
                                            <h3 style="font-family: Bnazanin"><a href="{% url "shop:product_detail" product.slug  %}">{{ product.title }}</a></h3>
                                            {% if product.exist %}
                                                <div class="price">
                                                    <ul>
                                                        {% if product.has_offer %}
                                                            <ul class="discount"> تومان {{ product.orginal_price }}</ul>
                                                            <ul> تومان {{ product.final_price }}</ul>
                                                        {% else %}
                                                            <ul> تومان {{ product.orginal_price }}</ul>
                                                        {% endif %}
                                                    </ul>
                                                </div>
                                            {% else %}
                                                <div class="price">
                                                    <ul>
                                                        <li class="product_dosent_exist">موجود نمی باشد</li>
                                                    </ul>
                                                </div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {#                        <div class="load_more_btn text-center">#}
                        {#                            <a href="#" class="btn_3">Load More</a>#}
                        {#                        </div>#}

                        <div class="load_more_btn ">
                                {% if is_paginated %}
                                    <nav class="pagination"  >
                                        <ul >
                                            {% if page_obj.has_previous %}
                                                <li><a href="?page={{ page_obj.previous_page_number }}">قبلی</a></li>
                                            {% else %}
                                                <li class="disabled"></li>
                                            {% endif %}
                                            {% for pages in page_obj.paginator.page_range %}
                                                {% if page_obj.number == pages %}
                                                    <li class="menuactive"><a href="#" style="color: white">{{ pages }}</a></li>
                                                {% else %}
                                                    <li><a href="?page={{ pages }}">{{ pages }}</a></li>
                                                {% endif %}
                                            {% endfor %}
                                            {% if page_obj.has_next %}
                                                <li><a href="?page={{ page_obj.next_page_number }}">بعدی</a></li>
                                            {% else %}
                                                <li class="disabled"></li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->

    <!-- client review part here -->
    <section class="client_review">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="client_review_slider owl-carousel">
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="{% static "/img/client.png" %}" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to
                                help
                                alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="{% static "/img/client_1.png" %}" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to
                                help
                                alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                        <div class="single_client_review">
                            <div class="client_img">
                                <img src="{% static "/img/client_2.png" %}" alt="#">
                            </div>
                            <p>"Working in conjunction with humanitarian aid agencies, we have supported programmes to
                                help
                                alleviate human suffering.</p>
                            <h5>- Micky Mouse</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- client review part end -->

    <!-- Shop Method Start-->
    <div class="shop-method-area section-padding30">
        <div class="container">
            <div class="row d-flex justify-content-between">
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-package"></i>
                        <h6>Free Shipping Method</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-unlock"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
                <div class="col-xl-3 col-lg-3 col-md-6">
                    <div class="single-method mb-40">
                        <i class="ti-reload"></i>
                        <h6>Secure Payment System</h6>
                        <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Shop Method End-->

    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>Get promotions & updates!</h2>
                        <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic”
                            sources credibly innovate granular internal .</p>
                        <div class="subscribe_form">
                            <input type="email" placeholder="Enter your mail">
                            <a href="#" class="btn_1">Subscribe</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->


{% endblock %}

templates/shop/category.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
{#    <!-- slider Area Start-->#}
{#    <div class="slider-area ">#}
{#        <!-- Mobile Menu -->#}
{#        <div class="single-slider slider-height2 d-flex align-items-center"#}
{#             data-background="{% static "/img/hero/category.jpg" %}">#}
{#            <div class="container">#}
{#                <div class="row">#}
{#                    <div class="col-xl-12">#}
{#                        <div class="hero-cap text-center">#}
{#                            <h2>محصولات</h2>#}
{#                        </div>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    <!-- slider Area End-->#}

    <!-- product list part start-->
    <section class="product_list section_padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="product_sidebar">
                        <div class="single_sedebar">
                            <form method="get" action="{% url "shop:product_search" %}" >
                                <input type="text" name="Search" value="{{ request.Get.q }}" placeholder="جستجوی محصول"
                                               style="direction: rtl; text-align: right; padding-right: 50px;">
                                <i class="ti-search"></i>
                            </form>

                        </div>
                        <div class="single_sedebar">
                            <div class="select_option" style="font-size: 120%">
                                <div class="select_option_list" style="text-align: right; padding-right: 50px">طبقه بندی<i
                                        class="right fas fa-caret-down"></i></div>
                                <div class="select_option_dropdown" style="text-align: right; padding-right: 50px">
                                    <pre><a href="{% url "shop:product_category" 'saltwater_fish'%}">ماهی آب شور</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'freshwater_fish'%}">ماهی آب شیرین</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'reef'%}">ریف</a></pre>
                                    <pre><a href="{% url "shop:product_category" 'supplies'%}">غذا و تجهیزات</a></pre>
                                </div>
                            </div>
                        </div>
                        {% if has_type %}
                            <div class="single_sedebar">
                                <div class="select_option">
                                    <div class="select_option_list"
                                         style="text-align: right; padding-right: 50px;font-size: 120%">نوع<i
                                            class="right fas fa-caret-down"></i></div>
                                    <div class="select_option_dropdown" style="text-align: right; padding-right: 50px;">
                                        {% for key, val in types.items %}
                                            <pre style="font-size: 120%"><a href="{% url "shop:product_category" key %}">{{ val }}</a></pre>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="product_list">
                        <div class="row">
                            {% for product in object_list %}
                                <div class="col-lg-6 col-sm-6">
                                    <div class="single_product_item">
                                        <a href="{% url "shop:product_detail" product.slug  %}"><img href="{{ product.slug }}" src="{{ product.image.url }}" alt="" class="img-fluid"></a>
                                        <div class="product-caption" style="text-align: center">
                                            <h3 style="font-family: Bnazanin"><a href="{% url "shop:product_detail" product.slug  %}">{{ product.title }}</a></h3>
{#                                            {% if product.exist %}#}
{#                                                <div class="price">#}
{#                                                    <ul>#}
{#                                                        {% if product.has_offer %}#}
{#                                                            <ul class="discount"> تومان {{ product.orginal_price }}</ul>#}
{#                                                            <ul> تومان {{ product.final_price }}</ul>#}
{#                                                        {% else %}#}
{#                                                            <ul> تومان {{ product.orginal_price }}</ul>#}
{#                                                        {% endif %}#}
{#                                                    </ul>#}
{#                                                </div>#}
{#                                            {% else %}#}
{#                                                <div class="price">#}
{#                                                    <ul>#}
{#                                                        <li class="product_dosent_exist">موجود نمی باشد</li>#}
{#                                                    </ul>#}
{#                                                </div>#}
{#                                            {% endif %}#}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                        {#                        <div class="load_more_btn text-center">#}
                        {#                            <a href="#" class="btn_3">Load More</a>#}
                        {#                        </div>#}

                        <div class="load_more_btn ">
                                {% if is_paginated %}
                                    {% include "_pagination.html" %}
                                {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- product list part end-->


{% endblock %}

templates/shop/product_detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}








    <!--================Single Product Area =================-->
    <!-- mobile view -->
    <div class="product_image_area d-block d-md-none section-padding40">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="product_img_slide owl-carousel">
                        {% for img in images %}
                            <div class="single_product_img">
                                <img src="{{ img.image.url }}" alt="#" class="img-fluid">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="single_product_text text-center">
                        <h3>{{ object.title }}</h3>
                        <p>
                            {{ object.description }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- large view -->
    <div class="product_image_area d-none d-md-block d-lg-none section-padding40">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="product_img_slide owl-carousel">
                        {% for img in images %}
                            <div class="single_product_img">
                                <img src="{{ img.image.url }}" alt="#" class="img-fluid">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="single_product_text text-right" dir="rtl" align="right">
                        <h3>{{ object.title }}</h3>
                        <pre>
                            {{ object.description }}
                        </pre>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- large view -->
    <div class="product_image_area d-none d-lg-block ">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="product_img_slide owl-carousel">
                        {% for img in images %}
                            <div class="single_product_img">
                                <img src="{{ img.image.url }}" alt="#" class="img-fluid">
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="single_product_text text-center">
                        <h3>{{ object.title }}</h3>
                        <pre>
                            {{ object.description }}
                        </pre>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <section class="related d-none d-sm-block" dir="rtl" style="color: red">
        <h3 align="right">محصولات مرتبط</h3>
        {% for related in related_products %}
            <div align="right" class="relatemovie">
                <a href="{% url "shop:product_detail" related.slug %}"><img src="{{ related.image.url }}"></a>
                <a href="{% url "shop:product_detail" related.slug %}"><span
                        class="relatedname align-right">{{ related.title }}</span></a>
            </div>
        {% endfor %}
    </section>



{% endblock %}